### PR TITLE
added type checking for gamera instance

### PR DESCRIPTION
**Pull request by flamendless**
This is useful for when user want to check if an object is of type 'gamera'

### CODE REVIEW

**Comment by kikito** [comment]
Hi, thank you for taking the time to write and send this Pull Request. Unfortunately, I must reject it. Here are my reasonings:

* The attach/dettach (or set/unset) discussion already happened many years ago [in the LÖVE forums](https://love2d.org/forums/viewtopic.php?f=5&t=12033). I don't wish to repeat myself so if you are interested, please visit the previous link. The short version is that I think attach/dettach is an inferior way of setting cameras and won't introduce it in mine. I understand that others might see things differently. You are more than welcome to keep those additions in your own fork. I won't mind. I think forks are great.
* With respect to `isCamera` or `.__camera`: my problem with those is that I can't think of a situation where they would be useful. Perhaps you could tell me the kind of problem you were trying to accomplish with them? All the situations I can think about can be easily implemented by putting an attribute on a table somewhere, whose implementation is smaller than what you added here.

**Comment by flamendless** [comment]
Hi there,
1. Using the `camera:draw(fn)` API can be a performance issue when passing an anonymous function that contains more draw codes (I've exp this in my project). Yes, users can create a non-anonymous function and use that instead but perhaps provide a note in README about that? Afaik most users (beginners) tend to do it the anonymous function way.
2. In my use case, having that type or attribute checking is useful for debugging/assertion checks. But yeah you're right, one can just set a new property to an instance but that would be repetitive let's say if you'll create a lot of cameras me

**Comment by kikito** [comment]
> perhaps provide a note in README about that?

That is a very good point, I might do just that.

(If you wish to send a PR which adds that explanation to the readme, feel free :) )

Thanks for contributing!

**Comment by flamendless** [comment]
PR submitted

**Pull request closed without merging**
